version: '3.4'

services:
  helloworld:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:80
  versionz:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - helloworld
